---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gh-actions-exporter
  labels:
    app.kubernetes.io/name: gh-actions-exporter
    app.kubernetes.io/instance: gh-actions-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gh-actions-exporter
      app.kubernetes.io/instance: gh-actions-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gh-actions-exporter
        app.kubernetes.io/instance: gh-actions-exporter
    spec:
      serviceAccountName: default
      containers:
      - name: gh-actions-exporter
        image: 'gh-actions-exporter:latest'
        imagePullPolicy: IfNotPresent
        args:
        - "--settings-file"
        - "/conf/settings.yml"
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        livenessProbe:
          initialDelaySeconds: 3
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 5
          httpGet:
            path: /
            port: http
        readinessProbe:
          initialDelaySeconds: 3
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 5
          httpGet:
            path: /
            port: http
        envFrom:
        - secretRef:
            name: gh-actions-exporter-env
        - configMapRef:
            name: gh-actions-exporter-env
        volumeMounts:
        - name: cache
          mountPath: /root/.gh-actions-exporter
        - name: config
          mountPath: /conf
        - name: temp
          mountPath: /tmp
      volumes:
      - name: cache
        emptyDir:
      - name: config
        secret:
          secretName: gh-actions-exporter-config
      - name: temp
        emptyDir:
