---
apiVersion: v1
kind: Service
metadata:
  name: gh-actions-exporter
  labels:
    app.kubernetes.io/name: gh-actions-exporter
    app.kubernetes.io/instance: gh-actions-exporter
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: gh-actions-exporter
    app.kubernetes.io/instance: gh-actions-exporter
